#!/bin/bash

echo && > pip6

x=1
MODE="+"
usr1()
{
	MODE="+"
}
trap 'usr1' SIGUSR1
usr2()
{
	MODE="*"
}
trap 'usr2' SIGUSR2
term()
{
	MODE="STOP"
}
trap 'term' SIGTERM

while true; do
	case "$MODE" in
		"+")
			let "x = $x + 2"
			;;
		"*")
			let "x = $x * 2"
			;;
		"STOP")
			echo "STOP"
			exit 0
			;;
	esac
	echo "$x"
	sleep 1
done
